- name: install nginx and start service
  hosts: web
  become: yes # equals -b in adhoc commands, getting root access

  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    name: nginx
    state: latest

  - name: start nginx
    ansible.builtin.service
    name: nginx
    state: started
    enabled: yes
