---
- name: Variables from files
  hosts: web
  become: yes
  tasks: 
  - name: Take variable values from files
    ansible.builtin.debug:
    msg: "I am {{Name}} working as {{Designation}} and Experience is {{Experience}}."
